module.exports = [
  ["box1", "contents"],
  ["box2", "contents"],
  ["box3", "contents"],
  ["box4", "contents"],
  ["box5", "contents"],
  ["box6", "contents"],
  ["box7", "contents"],
  ["box8", "contents"],
  ["box9", "contents"],
  ["box10", "contents"],
  ["box11", "contents"],
  ["box12", "contents"],
  ["box13", "contents"],
  ["box14", "contents"],
  ["box15", "contents"],
  ["box16", "contents"],
  ["box17", "contents"],
  ["box18", "contents"],
  ["box19", "contents"],
  ["box20", "contents"],
  ["box21", "contents"],
  ["box22", "contents"],
  ["box23", "contents"]
];
